# Generated by Django 2.2.13 on 2020-12-10 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_auto_20201022_1818"),
    ]

    operations = [
        migrations.AddField(
            model_name="friendlink",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name="邮件"),
        ),
    ]
